name: quiz_app
description: A Quiz App for the participants of the App Akademie.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  image_picker: ^1.0.4
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  http: ^1.1.0
  dio: ^5.3.3
  firebase_core: ^2.17.0
  cloud_firestore: ^4.9.3
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.6

flutter_launcher_icons:
  android: true  
  ios: true  
  image_path: "assets/icons/app_icon_2.png"

flutter_native_splash:
  color: "#111111"
  image: assets/icons/app_icon.png
  branding: assets/icons/splash_icon.png
  branding_mode: bottom

flutter:
  uses-material-design: true
  assets:
    - assets/images/