// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDkVg_rUdeucYpJL0pcaENmXSFLNYNsmcM',
    appId: '1:464729631584:web:ebc3c8785231bf8a634c05',
    messagingSenderId: '464729631584',
    projectId: 'batch-1-app',
    authDomain: 'batch-1-app.firebaseapp.com',
    storageBucket: 'batch-1-app.appspot.com',
    measurementId: 'G-1VJGQHFT0G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBEdExXdc8Zh6tymhSttQHgb89RMlLGH08',
    appId: '1:464729631584:android:600de7803f7ec024634c05',
    messagingSenderId: '464729631584',
    projectId: 'batch-1-app',
    storageBucket: 'batch-1-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLXzfinofcsdQN4JgtYbydEwe2oEuTa2Y',
    appId: '1:464729631584:ios:53082cd883b64be4634c05',
    messagingSenderId: '464729631584',
    projectId: 'batch-1-app',
    storageBucket: 'batch-1-app.appspot.com',
    iosBundleId: 'com.example.quizApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDLXzfinofcsdQN4JgtYbydEwe2oEuTa2Y',
    appId: '1:464729631584:ios:a6d28379ddb6125c634c05',
    messagingSenderId: '464729631584',
    projectId: 'batch-1-app',
    storageBucket: 'batch-1-app.appspot.com',
    iosBundleId: 'com.example.quizApp.RunnerTests',
  );
}
